version: '3'

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - ./api:/app
      - '/app/node_modules'
  mongo:
    container_name: mongo
    image: mongo:4.4
    ports:
      - 27017:27017
